config/routes.rb
PixelFire::Engine.routes.draw do
  resources :tags
  resources :triggers
  
  root to: "tags#index"
end

app/models/pixel_fire/application_record.rb
module PixelFire
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/pixel_fire/tag.rb
module PixelFire
  class Tag < ApplicationRecord
    has_many :tags_triggers
    has_many :triggers, through: :tags_triggers
    validates :name, presence: true, uniqueness: true
    validates :custom_html, presence: true

    def update_triggers(trigger_ids)
      trigger_ids  ||= []
      current_ids    = tags_triggers.pluck(:trigger_id)
      unchanged_ids  = trigger_ids & current_ids || []
      new_ids        = trigger_ids - unchanged_ids
      remove_ids     = current_ids - unchanged_ids

      tags_triggers.where(trigger_id: remove_ids).map(&:destroy) if remove_ids.present?
      new_ids.each do |trigger_id|
        tags_triggers.create(trigger_id: trigger_id)
      end
    end
  end
end

app/models/pixel_fire/tags_trigger.rb
module PixelFire
  class TagsTrigger < ApplicationRecord
    belongs_to :tag
    belongs_to :trigger
  end
end

app/models/pixel_fire/trigger.rb
module PixelFire
  class Trigger < ApplicationRecord
    has_many :tags_triggers
    has_many :tags, through: :tags_triggers
    validates :name, presence: true, uniqueness: true
    validates :page_url, presence: true, unless: -> (trigger) { trigger.fire_on_all_pages? }

    scope :matches, -> (path) do
      ids = []
      ::PixelFire::Trigger.pluck(:id, :page_url, :fire_on_all_pages).each do |vals|
        if vals[2] == true
          ids << vals[0]
        elsif path =~ Regexp.new(vals[1])
          ids << vals[0]
        end
      end
      if ids != []
        where(id: ids)
      else
        where("1 = 0")
      end
    end

    def update_tags(tag_ids)
      tag_ids      ||= []
      current_ids    = tags_triggers.pluck(:tag_id)
      unchanged_ids  = tag_ids & current_ids
      new_ids        = tag_ids - unchanged_ids
      remove_ids     = current_ids - unchanged_ids

      tags_triggers.where(tag_id: remove_ids).map(&:destroy) if remove_ids.present?
      new_ids.each do |tag_id|
        tags_triggers.create(tag_id: tag_id)
      end
    end
  end
end

app/controllers/pixel_fire/application_controller.rb
module PixelFire
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
  end
end

app/controllers/pixel_fire/tags_controller.rb
require_dependency "pixel_fire/application_controller"

module PixelFire
  class TagsController < ApplicationController
    before_action :set_tag, only: [:show, :edit, :update, :destroy]

    # GET /tags
    def index
      @tags = Tag.all
    end

    # GET /tags/1
    def show
    end

    # GET /tags/new
    def new
      @tag = Tag.new
    end

    # GET /tags/1/edit
    def edit
    end

    # POST /tags
    def create
      @tag = Tag.new(tag_params)

      if @tag.save
        @tag.update_triggers(params[:trigger_ids])
        redirect_to @tag, notice: 'Tag was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /tags/1
    def update
      if @tag.update(tag_params)
        @tag.update_triggers(params[:trigger_ids])
        redirect_to @tag, notice: 'Tag was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /tags/1
    def destroy
      @tag.destroy
      redirect_to tags_url, notice: 'Tag was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_tag
        @tag = Tag.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def tag_params
        params.require(:tag).permit(:name, :custom_html, :target)
      end
  end
end

app/controllers/pixel_fire/triggers_controller.rb
require_dependency "pixel_fire/application_controller"

module PixelFire
  class TriggersController < ApplicationController
    before_action :set_trigger, only: [:show, :edit, :update, :destroy]

    # GET /triggers
    def index
      @triggers = Trigger.all
    end

    # GET /triggers/1
    def show
    end

    # GET /triggers/new
    def new
      @trigger = Trigger.new
    end

    # GET /triggers/1/edit
    def edit
    end

    # POST /triggers
    def create
      @trigger = Trigger.new(trigger_params)

      if @trigger.save
        @trigger.update_tags(params[:tag_ids])
        redirect_to @trigger, notice: 'Trigger was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /triggers/1
    def update
      if @trigger.update(trigger_params)
        @trigger.update_tags(params[:tag_ids])
        redirect_to @trigger, notice: 'Trigger was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /triggers/1
    def destroy
      @trigger.destroy
      redirect_to triggers_url, notice: 'Trigger was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_trigger
        @trigger = Trigger.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def trigger_params
        params.require(:trigger).permit(:name, :fire_on_all_pages, :page_url)
      end
  end
end

app/helpers/pixel_fire/application_helper.rb
module PixelFire
  module ApplicationHelper
  end
end

app/helpers/pixel_fire/tags_helper.rb
module PixelFire
  module TagsHelper
  end
end

app/helpers/pixel_fire/triggers_helper.rb
module PixelFire
  module TriggersHelper
  end
end

app/views/layouts/pixel_fire/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PixelFire</title>
  
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

  <%= stylesheet_link_tag    "pixel_fire/application", media: "all" %>
  <%= javascript_include_tag "pixel_fire/application" %>
  
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">PixelFire</a>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li<% if controller_name == "tags" %> class="active"<% end %>><%= link_to "Tags", tags_path %></li>
        <li<% if controller_name == "triggers" %> class="active"<% end %>><%= link_to "Triggers", triggers_path %>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/pixel_fire/tags/_form.html.erb
<%= form_for(tag) do |f| %>
  <% if tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% tag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control", required: true %>
  </div>

  <div class="form-group">
    <%= f.label :target, "Embed Target" %>
    <%= f.select :target, ["head", "body"], {}, class: "form-control", required: true %>
  </div>

  <div class="form-group">
    <%= f.label :custom_html, "Custom HTML" %>
    <%= f.text_area :custom_html, class: "form-control", rows: 12, required: true %>
  </div>

  <div class="form-group">
    <label>Triggers</label>
    <ul class="list-unstyled">
    <% ::PixelFire::Trigger.all.order(name: :asc).each do |trigger| %>
      <li>
        <label style="font-weight: normal;">
          <input type="checkbox" name="trigger_ids[]"
                 value="<%= trigger.id %>" <%= "checked=\"checked\"" if tag.triggers.include?(trigger) %> />
          <%= trigger.name %>
        </label>
      </li>
    <% end %>
    </ul>
  </div>

  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/pixel_fire/tags/edit.html.erb
<h1 class="page-header">
  <%= link_to 'Back', tags_path, class: "pull-right btn btn-link" %>
  Edit Tag
</h1>

<%= render 'form', tag: @tag %>

app/views/pixel_fire/tags/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="page-header">
  <%= link_to 'New Tag', new_tag_path, class: "pull-right btn btn-default" %>
  Tags
</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Target</th>
      <th>Triggers</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%= tag.name %></td>
        <td><%= tag.target %></td>
        <td>
          <% tag.triggers.each do |trigger| %>
            <span class="label label-default"><%= trigger.name %></span>
          <% end %>
        </td>
        <td class="text-right">
          <%= link_to 'Show', tag, class: "btn btn-xs btn-info" %>
          <%= link_to 'Edit', edit_tag_path(tag), class: "btn btn-xs btn-primary" %>
          <%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-xs btn-danger" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/pixel_fire/tags/new.html.erb
<h1 class="page-header">
  <%= link_to 'Back', tags_path, class: "pull-right btn btn-link" %>
  New Tag
</h1>

<%= render 'form', tag: @tag %>

app/views/pixel_fire/tags/show.html.erb
<p id="notice"><%= notice %></p>

<h1 class="page-header">
  <%= link_to 'Back', tags_path, class: "pull-right btn btn-link" %>
  <%= link_to 'Edit', edit_tag_path(@tag), class: "pull-right btn btn-primary" %>
  Tag: <%= @tag.name %>
</h1>

<p>
  <strong>Name:</strong>
  <%= @tag.name %>
</p>

<p>
  <strong>Custom HTML:</strong>
  <pre><%= @tag.custom_html %></pre>
</p>

<p>
  <strong>Triggers:</strong>
  <ul>
    <% @tag.triggers.each do |trigger| %>
      <li><%= trigger.name %></li>
    <% end %>
  </ul>
</p>

app/views/pixel_fire/triggers/_form.html.erb
<%= form_for(trigger) do |f| %>
  <% if trigger.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(trigger.errors.count, "error") %> prohibited this trigger from being saved:</h2>

      <ul>
      <% trigger.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control", required: true %>
  </div>

  <div class="form-group">
    <%= f.check_box :fire_on_all_pages %>&nbsp;
    <%= f.label :fire_on_all_pages %>
  </div>

  <div class="form-group">
    <%= f.label :page_url, "URL Regex" %>
    <%= f.text_field :page_url, class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Tags</label>
    <ul class="list-unstyled">
    <% ::PixelFire::Tag.all.order(name: :asc).each do |tag| %>
      <li>
        <input type="checkbox" name="tag_ids[]"
               value="<%= tag.id %>" <%= "checked=\"checked\"" if trigger.tags.include?(tag) %> />
        <%= tag.name %>
      </li>
    <% end %>
    </ul>
  </div>

  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/pixel_fire/triggers/edit.html.erb
<h1 class="page-header">
  <%= link_to 'Back', triggers_path, class: "pull-right btn btn-link" %>
  Edit Trigger
</h1>

<%= render 'form', trigger: @trigger %>

app/views/pixel_fire/triggers/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="page-header">
  <%= link_to 'New Trigger', new_trigger_path, class: "pull-right btn btn-default" %>
  Triggers
</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>All Pages?</th>
      <th>URL Contains</th>
      <th>Tags</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @triggers.each do |trigger| %>
      <tr>
        <td><%= trigger.name %></td>
        <td><%= trigger.fire_on_all_pages %></td>
        <td><code><%= trigger.page_url %></code></td>
        <td>
          <% trigger.tags.each do |tag| %>
            <span class="label label-default"><%= tag.name %></span>
          <% end %>
        </td>
        <td class="text-right">
          <%= link_to 'Show', trigger, class: "btn btn-xs btn-info" %>
          <%= link_to 'Edit', edit_trigger_path(trigger), class: "btn btn-xs btn-primary" %>
          <%= link_to 'Destroy', trigger, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-xs btn-danger" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/pixel_fire/triggers/new.html.erb
<h1>New Trigger</h1>

<%= render 'form', trigger: @trigger %>

<%= link_to 'Back', triggers_path %>

app/views/pixel_fire/triggers/show.html.erb
<p id="notice"><%= notice %></p>

<h1 class="page-header">
  <%= link_to 'Back', triggers_path, class: "pull-right btn btn-link" %>
  <%= link_to 'Edit', edit_trigger_path(@trigger), class: "pull-right btn btn-primary" %>
  Trigger: <%= @trigger.name %>
</h1>

<p>
  <strong>Name:</strong>
  <%= @trigger.name %>
</p>

<p>
  <strong>Fire on all pages:</strong>
  <%= @trigger.fire_on_all_pages %>
</p>

<p>
  <strong>URL Contains:</strong>
  <code><%= @trigger.page_url %></code>
</p>

<p>
  <strong>Tags:</strong>
  <ul>
    <% @trigger.tags.each do |tag| %>
      <li><%= tag.name %></li>
    <% end %>
  </ul>
</p>